---
- name: Copy the node_exporter systemd service file
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart node_exporter

- name: Create node_exporter config directory
  ansible.builtin.file:
    path: "/etc/node_exporter"
    state: directory
    owner: root
    group: root
    mode: u+rwX,g+rwX,o=rX

- name: Copy the node_exporter config file
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /etc/node_exporter/config.yaml
    owner: root
    group: root
    mode: 0644
  notify: restart node_exporter

- name: Create textfile collector dir
  ansible.builtin.file:
    path: "{{ node_exporter_textfile_dir }}"
    state: directory
    owner: "{{ node_exporter_system_user }}"
    group: "{{ node_exporter_system_group }}"
    mode: u+rwX,g+rwX,o=rX
 
- name: Copy Custom scripts to the /var/lib/node_exporter
  ansible.builtin.copy:
    src: "{{ item.source }}"
    dest: "{{ node_exporter_textfile_dir }}"
    owner: "{{ node_exporter_system_user }}"
    group: "{{ node_exporter_system_group }}"
    mode: u+rwX
  loop: "{{ cron_jobs }}"
  loop_control:
    label: "{{ item.name }}" 
  when:
   - cron_jobs is defined

- name: Setup CronJob for the Custom Metrics
  ansible.builtin.cron:
    name: "{{ item.name }}"
    cron_file: "{{ item.file | default(omit) }}"
    job: "{{ item.job }}"
    state: present
    user: "{{ item.user | default(omit) }}"
    minute: "{{ item.minute | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    weekday: "{{ item.weekday | default(omit) }}"
    special_time: "{{ item.special_time | default(omit) }}"
  loop: "{{ cron_jobs }}"
  loop_control:
    label: "{{ item.name }}" 
  when:
   - cron_jobs is defined
    