- name: Configure sshd
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: "^(#)?{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
    state: present
  loop: "{{ sshd_config_items }}"

- name: Disable password based authentication 
  ansible.builtin.blockinfile:
    path: "/etc/ssh/sshd_config"
    block: |
       PasswordAuthentication no
       Match User !root
              PasswordAuthentication yes
    insertafter: EOF
    marker: "\n#<!-- {mark} ANSIBLE MANAGED BLOCK FOR SSH SETTINGS -->\n"
    state: present