- name: Copy Scripts Directory to root home Directory
  ansible.builtin.copy:
    src: scripts
    dest: /root/
    owner: root
    group: root
    mode: '0775'

- name: Copy ptp4l Directory to root home Directory
  ansible.builtin.copy:
    src: ptp4l
    dest: /root/
    owner: root
    group: root
    mode: '0775'    

- name: Run Script on Reboot
  ansible.builtin.cron:
    name: "Job on Reboot"
    special_time: reboot
    job: "$HOME/scripts/on_boot.sh"

- name: Schedule fix_fragmentation.sh at 00:05
  ansible.builtin.cron:
    name: "Fix fragmentation at 00:05"
    minute: "0"
    hour: "5"
    job: "{{ ansible_env.HOME }}/scripts/fix_fragmentation.sh"

- name: Schedule fix_fragmentation.sh at 00:08
  ansible.builtin.cron:
    name: "Fix fragmentation at 00:08"
    minute: "0"
    hour: "8"
    job: "{{ ansible_env.HOME }}/scripts/fix_fragmentation.sh"
