- import_tasks: 01_add_repository_for_toolchain.yml
  tags: toolchain  
- import_tasks: 02_install_kitware.yml 
  when: ansible_distribution_version == "20.04"
  tags: kitware
- import_tasks: 03_install_packages.yml
  tags: common_packages 
- import_tasks: 04_install_python_packages.yml
  tags: python_packages 
- import_tasks: 05_disable_ufw.yml
  tags: ufw 
- import_tasks: 06_disable_apport.yml
  tags: apport 
- import_tasks: 07_configure_kernel_core_pattern.yml
  tags: kernel_core_pattern 
- import_tasks: 08_configure_sshd.yml
  tags: setup_ssh 
- import_tasks: 09_set_kernel_grub_paramters.yml
  tags: kernel_grub 
- import_tasks: 10_stop_and_disable_irqbalance.yml
  tags: irqbalance 
- import_tasks: 11_update_editor_to_vim.yml
  tags: update_editor 
- import_tasks: 12_set_tuned_profile.yml
  tags: tuned_adm
- import_tasks: 13_add_group_showpid.yml
  tags: group_add
- import_tasks: 14_mounts_fstab.yml
  tags: fstab
- import_tasks: 15_replace_directory_mode_conf.yml
  tags: mode_conf
- import_tasks: 16_remove_execute_permission_update_motd.yml
  tags: update_motd 
- import_tasks: 17_set_timezone.yml
  tags: set_timezone 
- import_tasks: 18_remove_landscape_unattended_upgrades.yml
  tags: remove_unattended_upgrades 
- import_tasks: 19_set_default_target_multi_user.yml
  tags: multi_user_target 
- import_tasks: 20_setup_root_cronjobs.yml
  tags: cron_setup
- import_tasks: 21_install_exanic.yml
  tags: exanic_install
- import_tasks: 22_ipc.yml
  tags: ipc 
- import_tasks: 23_bashrc.yml
  tags: bashrc
- import_tasks: 24_vimrc.yml
  tags: vimrc 
- import_tasks: 25_static_hostname.yml
  when: static_hostname != ansible_hostname
  tags: hostname
- import_tasks: 26_Disable_wifi_drivers.yml
  tags: WiFi
- import_tasks: 27_Add_utility_users.yml
  tags: utility_users
- import_tasks: 28_prod_directory.yml
  tags: prod_directory