---
# vars file for common

common_packages_to_install:
  - build-essential
  - clang
  - cmake
  - cryptsetup
  - ecryptfs-utils
  - faketime
  - g++-13
  - gdb
  - gdbserver
  - git
  - htop
  - i7z
  - iotop
  - iputils-clockdiff
  - lftp
  - libcap-dev
  - libcurl4-openssl-dev
  - libfaketime
  - libgsl-dev
  - libjemalloc-dev
  - liblz4-dev
  - liblzma-dev
  - liblzo2-dev
  - libnl-3-dev
  - libnl-genl-3-dev
  - libpcap-dev
  - libpython3-dev
  - libssl-dev
  - libzstd-dev
  - linux-headers-{{ ansible_kernel }}
  - linuxptp
  - linux-tools-common
  - linux-tools-generic
  - linux-tools-{{ ansible_kernel }}
  - make
  - netcat-traditional
  - net-tools
  - network-manager
  - network-manager-openvpn
  - pkg-config
  - postfix
  - pybind11-dev
  - python3
  - python3-dev
  - python3-pip
  - r-base
  - screen
  - socat
  - sshfs
  - sysstat
  - tmux
  - tuned
  - vim
  - whowatch
  - zstd
  - ufw
  - openssh-server
  - irqbalance
  - cron
  - gcc-14 
  - g++-14
  - dos2unix
  - locate
  - tcpdump
  - tshark
  - fzf
  - jq
  - rsync
  - smartmontools
  - nvme-cli


apport_config_path: /etc/default/apport
apport_config_value: 'enabled=0'

timezone: Asia/Kolkata

kernel_core_pattern_path: /etc/sysctl.d/50-coredump.conf
kernel_core_pattern_value: core.%p.%e.%t

update_motd_script_path: /etc/update-motd.d/
update_motd_script_mode: 'a-x'

grub_config_path: /etc/default/grub
grub_config_line: 'GRUB_CMDLINE_LINUX=$GRUB_CMDLINE_LINUX "mce=ignore_ce nosoftlockup intel_idle.max_cstate=0 processor.max_cstate=0 mitigations=off isolcpus=0-7 nohz_full=0-7 rcu_nocbs=0-7 irqaffinity=8,9 selinux=0 audit=0 pcie_aspm=performance pci=noaer ipv6.disable=1"'

kitware_key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
kitware_keyring_path: /usr/share/keyrings/kitware-archive-keyring.gpg
kitware_repo_url: 'https://apt.kitware.com/ubuntu/'
kitware_repo_list_path: /etc/apt/sources.list.d/kitware.list

sshd_config_items:
  - { key: "PermitRootLogin", value: "yes" }
  - { key: "ClientAliveInterval", value: "30" }
  - { key: "ClientAliveCountMax", value: "3" }

toolchain_repository: ppa:ubuntu-toolchain-r/test

python_packages:
  - python3-yaml
  - python3-watchdog
  - python3-psutil
  - python3-pandas
  
exanic_version: v2.7.4

logind_conf: "/etc/systemd/logind.conf"
logind_ipc_value: "RemoveIPC=no"

bashrc_conf: "/etc/bash.bashrc"

vimrc_conf: "/etc/vim/vimrc"

users:
  - username: airflow
    shell: /bin/bash
    home: yes
    ssh_key: true
  - username: netadmin
    shell: /bin/bash
    home: yes
    sudo: yes
    sudo_cmnd: /usr/sbin/netplan, /usr/bin/vi /etc/netplan/ansible_netplan.yaml